services:
  - type: web
    name: video-compressor
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: UPLOADS_DIR
        value: /tmp/video-compressor-uploads
      - key: ALLOWED_ORIGINS
        value: https://sohaybteimsah.github.io,http://localhost:3000
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /tmp/video-compressor-uploads
      sizeGB: 1 